service: vision
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "rekognition:DetectLabels"
        - "rekognition:DetectFaces"
        - "s3:GetObject"
      Resource:
        - "*"

functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1_vision:
    handler: routes/v1.v1_vision
    events:
      - http:
          path: /v1/vision
          method: post
  v2_vision:
    handler: routes/v2.v2_vision
    events:
      - http:
          path: /v2/vision
          method: post
  v3_vision:
    handler: routes/v3.v3_vision
    events:
      - http:
          path: /v3/vision
          method: post
